### ISSUE TITLE
Qr code scanning not working

### ISSUE THREAD

**Issue by adhambadr** [HadeSoft/whatsgrab#1]
is this code still working ? grabbing the Qr code throwing it into an img object and attempting to scan is not working, therefore html stays at the Qr code page and the mouse select / click option is failing to find span

**Comment by VariousMilkshakes** [comment]
yeah sorry development is on hiatus, I could not figure out how to get it to grab the whole qr code. Even with a long load timeout the whole qr code wasn't loading.
I may return to it at a later date.

**Comment by adhambadr** [comment]
actually the whole Qr is being loaded. I adjusted the timeouts a bit and managed to popup a screen via open() to scan it. However this method used to work I believe before the end-to-end encryption. the new website now is sending some kind of token from the server
`<div class="qrcode idle" data-ref="<token>"></div>` which changes twice during the lifetime of a QR and the QR received is recalculated.

**Comment by VariousMilkshakes** [comment]
Ok cheers for the info, i'll have a look at it again and see make it work. Do you want to post or pull request the modifications you made?

**Comment by adhambadr** [comment]
my changes aren't really worth posting i just added after the qr code checkpoint : 
`fs.writeFileSync("test.html","<html><body><img src='"+code+"' /></body></html>");
open("test.html");`
I then moved on to this repo https://github.com/HadeSoft/whatsgrab it was a bit further down the line, but I gave up on this solution as it seems since April there is some kind of client side recalculation of the image based on key exchange. It needs some reverse engineering of the client-side code, I believe the whatsapp folks did to avoid phishing attacks of websites showing the Qr Code on their own webpage with "scan this with whatsapp to win a car" scams.
